name: Generate history

on:
    schedule:
        -cron: 0 * * * *

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
                with:
                    python-version: '3.8'
            - run: 
                - pip install .
                - flask generate-history
                - flask prune-history

        
